
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 4;
  public static final int CADENA = 32;
  public static final int DECIMAL = 31;
  public static final int DIVISION = 5;
  public static final int SUMA = 2;
  public static final int ETIQUETAS = 22;
  public static final int ERROR = 29;
  public static final int EJECUTAR = 28;
  public static final int PORCENTAJE = 34;
  public static final int TIPO = 25;
  public static final int DOS_PUNTOS = 8;
  public static final int VALORES = 23;
  public static final int BARRAS = 17;
  public static final int COMA = 14;
  public static final int TOTAL = 26;
  public static final int EOF = 0;
  public static final int DEF = 16;
  public static final int PIE = 18;
  public static final int CANTIDAD = 33;
  public static final int EXTRA = 27;
  public static final int PARENTESIS_C = 7;
  public static final int error = 1;
  public static final int PARENTESIS_A = 6;
  public static final int SIGNO_IGUAL = 15;
  public static final int LLAVE_C = 11;
  public static final int EJEY = 21;
  public static final int LLAVE_A = 10;
  public static final int PUNTO_COMA = 9;
  public static final int EJEX = 20;
  public static final int ENTERO = 30;
  public static final int CORCHETE_C = 13;
  public static final int UNIR = 24;
  public static final int CORCHETE_A = 12;
  public static final int TITULO = 19;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "SIGNO_IGUAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "ERROR",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CANTIDAD",
  "PORCENTAJE"
  };
}

