
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 7;
  public static final int CADENA = 2;
  public static final int DECIMAL = 4;
  public static final int DIVISION = 8;
  public static final int SUMA = 5;
  public static final int ETIQUETAS = 25;
  public static final int ERROR = 34;
  public static final int EJECUTAR = 33;
  public static final int PORCENTAJE = 30;
  public static final int TIPO = 28;
  public static final int DOS_PUNTOS = 11;
  public static final int VALORES = 26;
  public static final int BARRAS = 20;
  public static final int COMA = 17;
  public static final int TOTAL = 31;
  public static final int EOF = 0;
  public static final int DEF = 19;
  public static final int PIE = 21;
  public static final int EXTRA = 32;
  public static final int CANTIDAD = 29;
  public static final int PARENTESIS_C = 10;
  public static final int error = 1;
  public static final int SIGNO_IGUAL = 18;
  public static final int PARENTESIS_A = 9;
  public static final int LLAVE_C = 14;
  public static final int EJEY = 24;
  public static final int LLAVE_A = 13;
  public static final int PUNTO_COMA = 12;
  public static final int EJEX = 23;
  public static final int ENTERO = 3;
  public static final int CORCHETE_C = 16;
  public static final int UNIR = 27;
  public static final int CORCHETE_A = 15;
  public static final int TITULO = 22;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "SIGNO_IGUAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "ERROR"
  };
}

